### PR TITLE
Update Kaisa.cs

### PR DESCRIPTION
**Pull request by Syntaz**
Set kaisa Q to 645

### CODE REVIEW

**Comment by SiXZZZ** [comment]
Why 645?

**Comment by Syntaz** [comment]
It's since the range is center to center, so its hard to determine the exact value of the range(since it also depends on the enemy size https://leagueoflegends.fandom.com/wiki/Range)

Therefore I took the value which was the smooth and used also on other platforms.

**Comment by Syntaz** [comment]
Also this might be something that has to be fixed in the core for spellcasting (center to center)

**Comment by SiXZZZ** [comment]
I know how range works but at wiki it says 600 range and if you say center to center then 600 is correct. If you mean center to edge then add the targets boundingradius. If you mean edge to center then add kaisa boundingradius. If you mean edge to edge then add boundingradius for both kaisa and targets + 600. Cant see why it would be flat 645.

**Comment by SiXZZZ** [comment]
> Also this might be something that has to be fixed in the core for spellcasting (center to center)

What should change in the spellcasting of that. The range check just needs to be correct. Why would that need to change anything in core?

**Comment by Syntaz** [comment]
> > Also this might be something that has to be fixed in the core for spellcasting (center to center)
> 
> What should change in the spellcasting of that. The range check just needs to be correct. Why would that need to change anything in core?

Since it's not working correctly if the range of 600 is correct, since it clearly doesn't cast on max range

**Comment by SiXZZZ** [comment]
The distance check is how it is. Thats just vectors and distance between them so it doesnt make sense to change that. The problem is probably more likely to be that the spell is not center to center range or that the spell is not only 600 range. 645 just seems like an odd number to use.

**Comment by Syntaz** [comment]
Yeah i agree it's odd to use, but until the real calculation is there it's better then not casting imo, but feel free to check it :)

**Comment by SiXZZZ** [comment]
from what i can test the kaisa q range is center to edge = 600 range + target boundingradius

**Comment by SiXZZZ** [comment]
I have pushed a fix where it adds the bounding radius. I will close this pr. I mentioned you in the changelog on Oasys. Thanks for pointing it out!

**Pull request closed without merging**
